# Generated by Django 5.0.6 on 2024-06-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='categoria',
            new_name='genero',
        ),
        migrations.AddField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, default='fotoVacia.png', null=True, upload_to='vaLaCarpetaDondeEstaranLasFotos', verbose_name='Imagen del libro'),
        ),
    ]
