# Generated by Django 5.0.6 on 2024-06-07 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0002_rename_categoria_libro_genero_libro_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.SmallIntegerField(max_length=13, primary_key=True, serialize=False),
        ),
    ]
