# Generated by Django 5.0.6 on 2024-06-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0005_alter_libro_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, default='fotoVacia.png', null=True, upload_to='vaLaCarpetaDondeEstaranLasFotos', verbose_name='Foto de perfil'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='editorial',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='libro',
            name='isbn',
            field=models.CharField(max_length=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='libro',
            name='tipo',
            field=models.CharField(blank=True, choices=[('F', 'Fisico'), ('A', 'Audio'), ('E', 'Electronico')], max_length=1, null=True),
        ),
    ]
