# Generated by Django 5.0.4 on 2024-06-30 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0008_alter_libro_editorial_alter_libro_portada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='static/imagen/portadas', verbose_name='Imagen del libro'),
        ),
    ]
