# Generated by Django 5.0.4 on 2024-07-02 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicaciones', '0010_alter_libro_portada'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carrito',
        ),
    ]
